---
name: Build
"on":
  push:
    branches:
      - master
      - staging
      - develop
    tags:
      - v*
  pull_request:
    branches:
      - master
      - staging
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v3
      - name: Style
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          make style
      - name: Build
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          make all
      - name: Coveralls
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: cover.out
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v2
      - name: Build Release
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          make -j$(cat /proc/cpuinfo | grep processor | wc -l) release
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            reverseit-linux-arm64c
            reverseit-linux-x86_64
            reverseit-linux-i386
            reverseit-windows-i386.exe
            reverseit-windows-x86_64.exe
            reverseit-darwin-x86_64
            reverseit-darwin-arm64
            reverseit-freebsd-x86_64